#FOR EACH SERVICE
#spring:
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: UTC
#        order_inserts: true
#        order_updates: true
#        jdbc.batch_size: 50
#devbank:
#  datasource:
#    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
#    username: ACCOUNT
#    password: account
#    pool-size: 10
#  persistence:
#    open-in-view: false
#    ddl-auto: none
#    time-zone: UTC
#    jdbc-batch-size: 50
#    order-inserts: true
#    order-updates: true
#    jpa:
#      auditing-enabled: true
#    tx:
#      default-timeout-seconds: 30
