CREATE TABLE TRANSACTION (
            ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
            CURRENCY CHAR(3 CHAR) NOT NULL,
            AMOUNT NUMBER(19,4) NOT NULL CHECK (AMOUNT >= 0.01),
            EXTERNAL_REF VARCHAR2(100 CHAR),
            STATUS VARCHAR2(20 CHAR) NOT NULL,
            CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
            UPDATED_AT TIMESTAMP WITH TIME ZONE,
            POSTED_AT TIMESTAMP WITH TIME ZONE,
            FAILED_AT TIMESTAMP WITH TIME ZONE,
            CANCELED_AT TIMESTAMP WITH TIME ZONE,
            VERSION NUMBER(19,0),
            TRANSACTION_TYPE VARCHAR2(31 CHAR) NOT NULL
);

-- Index & Constraint
CREATE INDEX IX_TRANSACTION_STATUS ON TRANSACTION (STATUS);
CREATE UNIQUE INDEX UX_TRANSACTION_EXTERNAL_REF ON TRANSACTION (EXTERNAL_REF);


CREATE TABLE TRANSFER_TRANSACTION (
            ID RAW(16) PRIMARY KEY,
            FROM_ACCOUNT_ID RAW(16) NOT NULL,
            TO_ACCOUNT_ID RAW(16) NOT NULL,
            CONSTRAINT FK_TRANSFER_TRANSACTION FOREIGN KEY (ID)
            REFERENCES TRANSACTION(ID)
);

CREATE INDEX IX_TRANSFER_FROM ON TRANSFER_TRANSACTION (FROM_ACCOUNT_ID);
CREATE INDEX IX_TRANSFER_TO ON TRANSFER_TRANSACTION (TO_ACCOUNT_ID);


CREATE TABLE PAYMENT_TRANSACTION (
            ID RAW(16) PRIMARY KEY,
            PAYER_ID RAW(16) NOT NULL,
            MERCHANT_ID RAW(16) NOT NULL,
            BILL_REF VARCHAR2(500 CHAR) NOT NULL,
            CONSTRAINT FK_PAYMENT_TRANSACTION FOREIGN KEY (ID)
            REFERENCES TRANSACTION(ID)
);

-- ======================
-- OUTBOX TABLE
-- ======================
CREATE TABLE OUTBOX (
                        ID              RAW(16) DEFAULT SYS_GUID() NOT NULL,
                        AGGREGATETYPE   VARCHAR2(255 CHAR),
                        AGGREGATEID     VARCHAR2(255 CHAR),
                        TYPE            VARCHAR2(255 CHAR),
                        PAYLOAD         CLOB,
                        DESTINATION     VARCHAR2(255 CHAR),
                        IS_PUBLISHED    NUMBER(1,0) DEFAULT 0 NOT NULL,
                        CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

                        CONSTRAINT PK_OUTBOX PRIMARY KEY (ID),
                        CONSTRAINT CK_OUTBOX_IS_PUBLISHED CHECK (IS_PUBLISHED IN (0,1))
);

CREATE INDEX IX_IS_PUBLISHED ON OUTBOX (IS_PUBLISHED);

ALTER TABLE outbox ADD dtype VARCHAR2(31);


-- ======================
-- INBOX TABLE
-- ======================
CREATE TABLE INBOX (
                       IDEMPOTENT_TOKEN RAW(16) NOT NULL,
                       PAYLOAD CLOB,
                       TYPE VARCHAR2(255 CHAR),
                       IS_PROCESSED NUMBER(1,0) DEFAULT 0 NOT NULL,
                       RECEIVED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

                       CONSTRAINT PK_INBOX PRIMARY KEY (IDEMPOTENT_TOKEN),
                       CONSTRAINT CK_INBOX_IS_PROCESSED CHECH (IS_PROCESSED IN (0, 1))
);

CREATE INDEX IX_IS_PROCESSED ON OUTBOX (IS_PROCESSED);
